// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TMMoveEx","status":true,"description":"壁衝突音やリージョンによる通行設定などの機能を追加します。","parameters":{"passableRegionId":"251","dontPassRegionId":"252","seKnockWall":"<name:Blow1><volume:00><pitch:100>","knockWallPan":"75","knockWallInterval":"30","turnKeyCode":"0","movableRegion1":"1","movableRegion2":"","movableRegion3":"","movableRegion4":"","movableRegion5":"","movableRegion6":"","movableRegion7":"","movableRegion8":"","movableRegion9":"","movableRegion10":""}},
{"name":"Evtrig_Custum","status":true,"description":"イベント接触判定カスタマイズプラグイン","parameters":{"t_ev_trig":"0"}},
{"name":"UCHU_MobileOperation","status":true,"description":"スマホ操作用プラグイン。横持ち/縦持ちに対応した仮想ボタン、\r\nタッチ操作の方法を追加拡張し、スマホプレイを快適にします。","parameters":{"---PC Option---":"","PC BtnDisplay":"false","PC TouchExtend":"false","---File Path---":"","DPad Image":"./img/system/DirPad.png","ActionBtn Image":"./img/system/ActionButton.png","CancelBtn Image":"./img/system/CancelButton.png","---Button Customize---":"","Button Opacity":"0.5","Vertical BtnZoom":"1.7","Tablet BtnZoom":"0.8","TabVertical BtnZoom":"1.1","HideButton OnMessage":"true","DPad Visible":"true","DPad Size":"220","DPad Margin":"10; 5","DPad Orientation":"left; bottom","DPad OpelationRange":"1.3","DPad DiagonalRange":"0","ActionBtn Visible":"true","ActionBtn Size":"125","ActionBtn Margin":"10; 75","ActionBtn Orientation":"right; bottom","CancelBtn Visible":"true","CancelBtn Size":"100","CancelBtn Margin":"110; 10","CancelBtn Orientation":"right; bottom","---TouchInput Extend---":"","Flick PageUp-PageDown":"false","HoldCanvas ActionBtn":"false","OutCanvas CancelBtn":"false","OutCanvas ActionBtn":"false","--!need AnalogMove.js!--":"","Analog Move":"false","Analog Sensitivity":"1.8"}},
{"name":"CustomizeConfigDefault","status":true,"description":"オプションデフォルト値設定プラグイン","parameters":{"常時ダッシュ":"ON","コマンド記憶":"OFF","BGM音量":"100","BGS音量":"100","ME音量":"100","SE音量":"100","常時ダッシュ消去":"OFF","コマンド記憶消去":"OFF","BGM音量消去":"OFF","BGS音量消去":"OFF","ME音量消去":"OFF","SE音量消去":"OFF"}},
{"name":"BugFixParallelEventAndCharacter","status":true,"description":"並列処理イベントのセーブ失敗バグ修正プラグイン","parameters":{}},
{"name":"SAN_AnalogMove","status":true,"description":"アナログムーブ 3.1.0\r\nパーティキャラクターの移動をドット移動に変更します。","parameters":{}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"TemplateEvent","status":true,"description":"テンプレートイベントプラグイン","parameters":{"テンプレートマップID":"0","イベントIDを維持":"true","上書き禁止":"false"}}
];
